# This is a basic workflow to help you get started with Actions

name: Artifact upload test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Upload at working dir
        uses: actions/upload-artifact@v3
        with:
          name: "pyArtifact"
          path: tableTest.py
  consume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "pyArtifact"
          path: .action

      - name: Confirm download
        shell: bash
        run: |
          echo "pwd ls"
          ls
          cd .auto
          echo ".auto/ ls"
          ls
