# This is a basic workflow to help you get started with Actions

name: Cache Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          mkdir -p first/second
          touch first/second/file.txt
          echo "pwd ls"
          ls
          echo "first ls"
          ls first/
          echo "second ls"
          ls first/second/
          echo "cachePath=first/second/file.txt" >> $GITHUB_ENV
      
      - name: Cache Artifact
        uses: actions/cache/save@v3
        with:
          path: ${{ env.cachePath }}
          key: artifact-${{ github.run_id }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          path: ${{ env.cachePath }}
          
      - name: Restore Artifact
        uses: actions/cache/restore@v3
        with:
          path: first/
          key: artifact-${{ github.run_id }}
          restore-keys: |
            artifact-
            artifact
            
      - name: Confirm restore
        run: |
          echo "pwd ls"
          ls
          echo "first ls"
          ls first/
          echo "second ls"
          ls first/second/
          
