# This is a basic workflow to help you get started with Actions

name: Input test

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Default test
        env:
          INPUT: ${{ inputs.test || 'Default' }}
        shell: bash
        run: |
          echo "Input variable"
          echo "$INPUT"
          echo "After input variable"
      
      - name: Skip if not set
        if: ${{ inputs.test != '' }}
        shell: bash
        run: |
          echo "Ruh Roh"

      - name: Skip in composite action
        uses: ./.github/composite-actions/input-test-comp
